package com.niyaj.ui.util

val slogans = listOf(
        "Life is too short for bad food.",
        "Farm to table, family-style.",
        "Food with soul.",
        "Eat well. Do good.",
        "The local favorite.",
        "Let’s Eat.",
        "Good Food, Good Mood.",
        "Good Food, Good life.",
        "Live to Eat.",
        "The magic of the kitchen.",
        "Food lovers unite.",
        "Spice it up.",
        "The place for real food.",
        "Eat your heart out.",
        "Eating is always a good idea.",
        "Where food meets soul.",
        "The best memories are shared.",
        "Savor the flavors.",
        "If you’re hungry, come on in!",
        "Fine dining, without the pretension.",
        "Where every ingredient tells a story.",
        "Where your food dreams come true.",
        "The Good Food Experience.",
        "There’s a recipe for every life.",
        "To eat is to live.",
        "Fresh food, fresh ideas.",
        "Delicious food with meaning",
        "Food with a story.",
        "Taste the rainbow.",
        "The flavors of life are just a bite away.",
        "A feast for all five senses.",
        "Come for the food, stay for the atmosphere.",
        "Deliciously modern.",
        "Perfection is not a destination but a journey.",
        "A sensory experience.",
        "A new way to experience food.",
        "True ingredients, true flavors.",
        "Good food doesn’t need to be complicated.",
        "The finest cuisine is close to home.",
        "Good Food in a Friendly Place.",
        "Food with a smile.",
        "The taste you’ll remember.",
        "Each day, a new tasting experience.",
        "The best ingredients, simply prepared.",
        "Nurture your passion for food and life.",
        "An unforgettable meal.",
        "Fresh is the taste.",
        "An experience you won’t forget.",
        "The most important meal of the day.",
        "Something you’ll remember.",
        "We give food a flavor.",
        "Follow your taste.",
        "A dining experience worth sharing.",
        "The best food, made by good people.",
        "Come eat with us.",
        "Let’s enjoy a meal together.",
        "Let’s get back to the kitchen table.",
        "Enjoy pure,natural food that tastes amazing.",
        "A modern take on the classic diner.",
        "When you are hungry, we will feed you.",
        "We cook simple food. For real.",
        "Our burgers are made for meat lovers.",
        "This is what a burger should taste like.",
        "BBQ made with real fire.",
        "When it comes to BBQ, we’re the experts.",
        "Leave with a full stomach and a happy heart.",
        "The fire inside.",
        "It’s a neighborhood gem.",
        "A hearty meal for the hunter in all of us.",
        "When you’re here, you’re family.",
        "The tradition continues.",
        "Where food comes first.",
        "An intimate and exclusive experience",
        "Fine food in a unique environment.",
        "A place where food lovers come to eat.",
        "The good life is waiting for you.",
        "Come for a drink, stay for a meal.",
        "A destination for food lovers.",
        "Fine dining with a contemporary edge.",
        "The future of fine dining.",
        "We grow on you.",
        "A fresh, green approach.",
        "Bringing the seasons to your plate.",
        "Local. Organic. Every Season.",
        "We make vegetables sexy.",
        "We eat what we grow.",
        "Organic and delicious.",
        "Little taste of all the seasons.",
        "Eat in the right season.",
        "The greatest things come from the earth.",
        "Seasonal food at its best.",
        "Serving the best of the season.",
        "Food that feeds your soul.",
        "Enjoy the benefits of a healthy, delicious meal.",
        "Vegetables are the star.",
    )